script_file: run_gold.py
env: ccdc_env
ligand_in_format: mol #'mol': '.sdf'
ligand_out_format: sdf
input_arg_name: --ligand
output_arg_name: --out
score_mode: max

program_args:
  config: NADPH/gold.conf

parse_score:
  score_field: docking_score
